'''
 This file is to demonstrate a Bitcoin transaction between my personal bitcoin address
 on Binance and my generated Bitcoin address (37jmZPPtUTsNYsA3G8SXxRjNNM6H3yfqQT) for user Nazareth.
 I used my binance account to send 0.0002 BTC to this wallet, and then sent back 0.0001 BTC
 twice with two different transactions, back to my binance wallet.
 All credentials such as secret vector, secret key, public key, and P2SH (BASE58) - Segwit - Pay to Script Hash
 wallet address are stored in my_credentials.json and generated by main.py with testnet set to False
 Details about the transactions can be found here:
 https://www.blockchain.com/explorer/addresses/btc/37jmZPPtUTsNYsA3G8SXxRjNNM6H3yfqQT
'''

from cryptos import Bitcoin, serialize
c = Bitcoin(testnet=False)
Nazareth_SecretKey = "5bc0ae48b46a66729923c26a11ba96b9208567eb4bbe97c1014d83458d8b105f" # secret key and address are generated by main.py and saved in my_credentials.json
Nazareth_address = "37jmZPPtUTsNYsA3G8SXxRjNNM6H3yfqQT" 
Nazareth_utxos = c.unspent(Nazareth_address)

if len(Nazareth_utxos) == 0:
    print("Nazareth Test User has no UTXOs available")
    exit(1)
print("Nazareth Test UTXOs:",Nazareth_utxos)

# Now let's try to send the BTC back to my Binance Bitcoin address
Nazareth_Binance_address = "1FwgDsedmKcKjmEZJUKuYSVp8K7RXHvZsW"
txin = Nazareth_utxos[0]
try:
    tx =  c.send(Nazareth_SecretKey, Nazareth_address, Nazareth_Binance_address, 1000)
    sig = serialize(tx)
    res = c.pushtx(tx)
    print("signature:", sig)
    print("result:", res)
except Exception as e:
    print(f"An exception occurred: {e}")

# Output before the transaction
# Nazareth Test UTXOs: [{'tx_hash': 'dd75a4cfee3ad046f814d7b4d6478a47db3eb76dc3518f1caee192e02a9f17a1', 
# 'tx_pos': 14, 'height': 814124, 'value': 14000, 'address': '37jmZPPtUTsNYsA3G8SXxRjNNM6H3yfqQT'}]

#Output after the transaction
# Nazareth Test UTXOs: [{'tx_hash': '04ca76de99d944d43577737356705bc338858f97855d8de9de7bbe2dbfa60107',
#  'tx_pos': 1, 'height': 0, 'value': 3106, 'address': '37jmZPPtUTsNYsA3G8SXxRjNNM6H3yfqQT'}]


